#!/bin/sh
setxkbmap -option altwin:swap_lalt_lwin
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
xiccd &
xrdb -merge ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
unclutter &
redshift &
